# Generated by Django 5.2.13 on 2026-05-01 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_latitude_profile_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Аватарка'),
        ),
        migrations.AddField(
            model_name='profile',
            name='favorite_player',
            field=models.CharField(blank=True, max_length=100, verbose_name='Любимый игрок'),
        ),
        migrations.AddField(
            model_name='profile',
            name='favorite_team',
            field=models.CharField(blank=True, max_length=100, verbose_name='Любимая команда'),
        ),
        migrations.AddField(
            model_name='profile',
            name='shirt_size',
            field=models.CharField(blank=True, choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL')], max_length=5, verbose_name='Размер формы'),
        ),
    ]
