# Generated by Django 5.2.13 on 2026-05-04 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='gender',
            field=models.CharField(choices=[('male', 'Мужское'), ('female', 'Женское'), ('kids', 'Детское'), ('unisex', 'Унисекс / Инвентарь')], default='unisex', max_length=10, verbose_name='Пол / Категория'),
        ),
    ]
